# Generated by Django 3.2.8 on 2021-10-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='expire_pack',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
