# Generated by Django 3.2.8 on 2021-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_package_expire_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='expire_pack',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
