# Generated by Django 3.2.4 on 2021-10-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_package_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
